include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - require_trailing_commas
    - directives_ordering
    - lines_longer_than_80_chars
analyzer:
  exclude: [test/**.g.dart, test/**.mocks.dart]
  errors:
    always_use_package_imports: error
    avoid_dynamic_calls: error
    avoid_empty_else: error
    avoid_print: error
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    require_trailing_commas: error
    directives_ordering: warning
    lines_longer_than_80_chars: error